### ISSUE TITLE
more info?

### ISSUE THREAD

**Issue by MasterEvilAce** [SzKristof97/EnemyFix#1]
can you explain the problem in more detail?

how do you know enemies are not despawning and what are the symptoms?

I've tried to find bug reports relating to this and nobody is talking about it. So I'm unsure if there really is an issue?

**Comment by SzKristof97** [comment]
Sure thing,

I'm not really 100% sure it is a general game bug or caused by a mod.
We usually play with around 20-30 mods but theres only a few that actually do something with the generation or spawning system like the better brutal events.

The problem was after we left the moon some or almost all of the spawned enemies stayed where they were. (basicly they not despawned).

We tried to remove the mods one by one and reinstalling the game as well but the bug never get solved.
Depending on the console error i've got i figured out it could be a bug in the game.

This mod basicly just force the enemies to despawn on the server side and that forces the clients to despawn the enemies as well.

I seen this bug before i encountered with it in a few TikTok and youtube shorts videos

**Comment by SzKristof97** [comment]
With my friends we tested it and works well with the other mods, so if it caused by one of them this should get rid of the bug.
